export const SET_LOADER = 'SET_LOADER', RESET_LOADER = 'RESET_LOADER',
LOGIN = 'LOGIN', LOGOUT = 'LOGOUT', SIGNUP = 'SIGNUP';
export const GET_PROJECT='GET_PROJECT', GET_PROJECTS='GET_PROJECTS', UPDATE_PROJECT='UPDATE_PROJECT', CREATE_PROJECT='CREATE_PROJECT',DELETE_PROJECT='DELETE_PROJECT',REDIRECT_URI='REDIRECT_URI';
export const GET_USER='GET_USER', GET_USERS='GET_USERS', UPDATE_USER='UPDATE_USER', CREATE_USER='CREATE_USER',DELETE_USER='DELETE_USER', USER_ACTION_PERFORMED = 'USER_ACTION_PERFORMED',URER_REDIRECT_URI='URER_REDIRECT_URI',COPY_CREDENTIALS='COPY_CREDENTIALS';
export const GET_TASK = 'GET_TASK',
  GET_REPORT_TASK = 'GET_REPORT_TASK',
  GET_REPORT_TASK_SUCCESS = 'GET_REPORT_TASK_SUCCESS',
  GET_REPORT_TASK_FAILED = 'GET_REPORT_TASK_FAILED',
  GET_TASKS = 'GET_TASKS',
  UPDATE_TASK = 'UPDATE_TASK',
  CREATE_TASK = 'CREATE_TASK',
  DELETE_TASK = 'DELETE_TASK';
export const GET_ROLES='GET_ROLES';
export const GET_COMMENT='GET_COMMENT',GET_COMMENTS='GET_COMMENTS',UPDATE_COMMENT='UPDATE_COMMENT',CREATE_COMMENT='CREATE_COMMENT'
export const GET_SKILLS='GET_SKILLS',DELETE_PROPOSAL='DELETE_PROPOSAL',GET_CHANNELS='GET_CHANNELS',GET_BID_STATUS='GET_BID_STATUS',CREATE_PROPOSAL='CREATE_PROPOSAL',GET_PROPOSALS='GET_PROPOSALS',GET_PROPOSAL_TYPE='GET_PROPOSAL_TYPE',
  GET_PROPOSAL_BY_ID='GET_PROPOSAL_BY_ID',UPDATE_PROPOSAL='UPDATE_PROPOSAL',DELETE_PROPOSAL_DOCUMENT='DELETE_PROPOSAL_DOCUMENT',GET_BID_STATS='GET_BID_STATS', GET_GRAPH='GETGRAPH',GET_COUNTRIES='GET_COUNTRIES',
  GET_PROFILES='GET_PROFILES',CHANGE_STATUS='CHANGE_STATUS',ADD_SKILLS='ADD_SKILLS',GET_PROFILE_BY_ID='GET_PROFILE_BY_ID',GET_CLIENTS='GET_CLIENTS',CREATE_SKILLS='CREATE_SKILLS',PROFILE_CREATED='PROFILE_CREATED',
  UPDATE_PROFILE='UPDATE_PROFILE',GET_STATUS='GET_STATUS',UPDATE_SKILL='UPDATE_SKILL', GET_SKILL_BY_ID='GET_SKILL_BY_ID',BID_STATUS='BID_STATUS',CREATE_STATUS='CREATE_STATUS',
  UPDATE_STATUS='UPDATE_STATUS',GET_STATUS_BY_ID='GET_STATUS_BY_ID',ADD_COMMENT='ADD_COMMENT',ADD_CLIENT='ADD_CLIENT',GET_CLIENT_BY_ID='GET_CLIENT_BY_ID',UPDATE_CLIENT='UPDATE_CLIENT'
  ;